name: notify_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  uuid: ^4.5.1
  sqflite_common_ffi: 2.3.0
  sqlite3_flutter_libs: 0.5.20
  supabase_flutter: ^2.12.0
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  timezone: ^0.10.1
  flutter_colorpicker: ^1.1.0
  share_plus: ^10.1.0
  record: ^6.1.2
  audioplayers: ^5.2.1
  path_provider: ^2.1.2
  local_auth: ^2.1.6  # For Fingerprint/FaceID
  intl_phone_field: ^3.2.0 # For clean SMS phone input

flutter:
  uses-material-design: true

dependency_overrides:
  js: ^0.7.1